In [2]:
# Import library pyTorch
import torch

In [2]:
#1. create 1D and 2D tensors
a = torch.tensor([1, 2, 3])
print("1D Tensor:", a)

b = torch.tensor([[1,2], [3, 4]])
print("2D Tensor:\n", b)

1D Tensor: tensor([1, 2, 3])
2D Tensor:
 tensor([[1, 2],
        [3, 4]])


In [3]:
# 2. Create random 3x3 tensor
c = torch.rand(3, 3)
print("Random 3x3 Tensor:\n", c)

Random 3x3 Tensor:
 tensor([[0.0033, 0.1753, 0.2726],
        [0.3168, 0.2640, 0.8158],
        [0.1986, 0.5142, 0.6487]])


In [4]:
# 3. Basic Tensor Operations
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

print("x + y: ", x + y)
print("x * y (element-wise):", x * y)
print("Dot produxt:", torch.dot(x, y))

x + y:  tensor([5., 7., 9.])
x * y (element-wise): tensor([ 4., 10., 18.])
Dot produxt: tensor(32.)


In [5]:
# 4. Reshape a tensor
z = torch.rand(4, 4)
print("Original Shape:", z.shape)
print("Reshape to 2 x 8:\n", z.view(2, 8))

Original Shape: torch.Size([4, 4])
Reshape to 2 x 8:
 tensor([[9.4911e-01, 8.3503e-01, 9.1258e-01, 8.1193e-01, 4.3683e-01, 4.8787e-01,
         3.3631e-01, 6.7781e-01],
        [3.6454e-01, 6.4761e-01, 2.3902e-01, 6.0285e-01, 5.0060e-01, 5.0946e-01,
         7.7975e-04, 7.3317e-01]])


In [6]:
# 5. Indexing and Slicing
mat = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("first row:", mat[0])
print("Elemen at (1, 2)", mat[1, 2])
print("All row, column 2:", mat[:, 1])

first row: tensor([1, 2, 3])
Elemen at (1, 2) tensor(6)
All row, column 2: tensor([2, 5])


In [7]:
# move tensor to GPU (if available)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("using device:", device)

x_gpu = torch.rand(3, 3).to(device)
print("Tensor on device:", x_gpu.device)

using device: cpu
Tensor on device: cpu


In [ ]:
# TODO:
# 1. Create a 2x3 tensor with random values
# 2. Create another 2x3 tensor and perform addition and multiplication
# 3. Reshape the tensor to 3x2
# 4. Move the tensor to GPU (if available) and print the device

# Write your code below...

In [8]:
# 1. create a 2 x 3 tensor with random values
d = torch.rand(2, 3)
print("Random 2x3 Tensor:\n", d)

Random 2x3 Tensor:
 tensor([[0.0109, 0.0946, 0.4189],
        [0.7569, 0.7186, 0.6143]])


In [9]:
# 2. Create another 2 x 3 tensor and perform addition and multiplication
e = torch.rand(2, 3)

# Element-wise addition
added = d + e

# element-wise multiplication
multuplied = d * e

print("Tensor A:\n", d)
print("Tensor B:\n", e)
print("Added:\n", added)
print("Multiplied:\n", multuplied)

Tensor A:
 tensor([[0.0109, 0.0946, 0.4189],
        [0.7569, 0.7186, 0.6143]])
Tensor B:
 tensor([[0.8267, 0.9674, 0.7794],
        [0.5159, 0.3192, 0.6642]])
Added:
 tensor([[0.8376, 1.0620, 1.1983],
        [1.2728, 1.0378, 1.2785]])
Multiplied:
 tensor([[0.0090, 0.0915, 0.3265],
        [0.3905, 0.2294, 0.4080]])


In [10]:
# 3. Reshape tensor to 3x2
reshaped = d.view(3,2)
print("Reshaped Tersor A:\n", reshaped)

Reshaped Tersor A:
 tensor([[0.0109, 0.0946],
        [0.4189, 0.7569],
        [0.7186, 0.6143]])


In [11]:
# 4. Move tensor to GPU(if available)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

tensor_gpu = d.to(device)
print("Tensor A is on:", tensor_gpu.device)

Tensor A is on: cpu
